# Generated by Django 5.0.1 on 2024-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_ticket_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('CREATED', 'Créé'), ('REQUEST', 'Demande')], default='CREATED', max_length=10),
        ),
    ]
