# Generated by Django 5.0.1 on 2024-01-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('CREATED', 'Créé'), ('REQUEST', 'Demande')], max_length=10),
        ),
    ]
